name: Scheduled Add Flare Funds test
on:
  schedule:
    - cron: "0 9 * * 5"
  workflow_dispatch:

jobs:
  Add-Flare-funds-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run addFundsToWallet test
        run: npm run addFunds

    # Create a channel on slack a try to import notif for workflow
